name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install packages and build
      run: |
        npm install
        npm run build
      env:
        CI: false

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        external_repository: exquiro/exquiro.github.io
        publish_dir: ./build
        publish_branch: master
